### ISSUE TITLE
Resolve `function static(){'use strict';}`

### ISSUE THREAD

**Issue by bakkot** [tc39/test262-parser-tests#13]
See https://github.com/tc39/test262-parser-tests/issues/8#issuecomment-302775433, https://github.com/tc39/ecma262/issues/632, https://bugs.ecmascript.org/show_bug.cgi?id=4243.

**Comment by bakkot** [comment]
The spec should be clarified, and the three of {ecma262, test262, test262-parser-tests} should be made to agree.

**Comment by michaelficarra** [comment]
And, of course, implementations.

**Comment by bakkot** [comment]
Oh, right. Those too.

**Comment by RReverser** [comment]
Should we maybe disable (as in, move to separate folder) tests that are controversial due to this for now? Would help with the integration of the test suite to other parsers.

**Comment by michaelficarra** [comment]
@RReverser I think it's best for the tests to reflect exactly what is in the spec, as is done in test262. Even if we think we are going to change it or if all implementations agree on something else. All implementations that integrate with test262 already maintain a test262 test blacklist. It's not much of a burden to maintain another for the parser tests.

**Comment by RReverser** [comment]
@michaelficarra In this case test262 and implementations disagree with parser tests. Until this is further clarified, it would be nice to have it explicitly stated as controversial.

**Comment by bakkot** [comment]
Fixed by #17 / https://github.com/tc39/ecma262/pull/1158.
