### ISSUE TITLE
`for (;;)` marked 'fail', should be 'pass'

### ISSUE THREAD

**Issue by jmdyck** [tc39/test262-parser-tests#18]
The content of `fail/3e6146fd7daff493.js` is: `for(;;)`
I believe ASI rule 2 makes this a valid script, so it should be in `pass`.

**Comment by bmeck** [comment]
agreed, ASI should convert it to ~ `for(;;);` which is valid, per reason above

quick ref link: https://tc39.github.io/ecma262/#sec-rules-of-automatic-semicolon-insertion

**Comment by michaelficarra** [comment]
No, I think it's right. ASI can't insert empty statements.

> However, there is an additional overriding condition on the preceding rules: a semicolon is never inserted automatically if the semicolon would then be parsed as an empty statement or if that semicolon would become one of the two semicolons in the header of a for statement (see 13.7.4).

**Comment by jmdyck** [comment]
Ah! Thanks.
(It's unfortunate there aren't explanations to accompany at least some tests.)

**Comment by michaelficarra** [comment]
An explanation for a non-program doesn't really make sense to me. I guess we could describe the production that is being parsed when the parse fails? But that doesn't seem too useful.

Explanations for programs already exist in the "explicit" examples.
