### ISSUE TITLE
Invalid for-of test

### ISSUE THREAD

**Issue by Protryon** [tc39/test262-parser-tests#24]
The following test is invalid:

* `ef2d369cccc5386c.js`

**Comment by bakkot** [comment]
No, it isn't (my bad). for-of statements [do not allow](https://tc39.github.io/ecma262/#sec-iteration-statements) `let` as the lookahead for a LeftHandSideExpression, unlike for-in statements.

(v8 [has a bug](https://bugs.chromium.org/p/v8/issues/detail?id=9160&q=&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars) permitting this.)
